/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPointsLedger__factory } from "./IPointsLedger__factory";
export { IScoreRegistry__factory } from "./IScoreRegistry__factory";
export { IStakingVault__factory } from "./IStakingVault__factory";
