/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IScoreRegistry,
  IScoreRegistryInterface,
} from "../../interfaces/IScoreRegistry";

const _abi = [
  {
    inputs: [],
    name: "CHALLENGE_WINDOW",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
    ],
    name: "getPendingProposal",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "id",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "popId",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "score",
            type: "uint64",
          },
          {
            internalType: "int64",
            name: "totalPoints",
            type: "int64",
          },
          {
            internalType: "bytes32",
            name: "eventsRoot",
            type: "bytes32",
          },
          {
            internalType: "uint32",
            name: "eventCount",
            type: "uint32",
          },
          {
            internalType: "uint64",
            name: "sourceBlockHeight",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "algorithmVersion",
            type: "uint16",
          },
          {
            internalType: "uint64",
            name: "proposedAt",
            type: "uint64",
          },
          {
            internalType: "address",
            name: "proposer",
            type: "address",
          },
          {
            internalType: "enum IScoreRegistry.ProposalStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct IScoreRegistry.ScoreProposal",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "disputeId",
        type: "uint64",
      },
    ],
    name: "markDisputed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "disputerWins",
        type: "bool",
      },
      {
        internalType: "uint64",
        name: "correctedScore",
        type: "uint64",
      },
      {
        internalType: "int64",
        name: "correctedPoints",
        type: "int64",
      },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IScoreRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IScoreRegistryInterface {
    return new Interface(_abi) as IScoreRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IScoreRegistry {
    return new Contract(address, _abi, runner) as unknown as IScoreRegistry;
  }
}
