/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStakingVault,
  IStakingVaultInterface,
} from "../../interfaces/IStakingVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
    ],
    name: "extendLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
    ],
    name: "getStake",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "amount",
            type: "uint128",
          },
          {
            internalType: "uint64",
            name: "stakedAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "lockUntil",
            type: "uint64",
          },
          {
            internalType: "bool",
            name: "isLocked",
            type: "bool",
          },
        ],
        internalType: "struct IStakingVault.StakeRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
    ],
    name: "hasActiveStake",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "popId",
        type: "bytes32",
      },
    ],
    name: "releaseLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStakingVault__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingVaultInterface {
    return new Interface(_abi) as IStakingVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStakingVault {
    return new Contract(address, _abi, runner) as unknown as IStakingVault;
  }
}
