/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IStakingVault {
  export type StakeRecordStruct = {
    amount: BigNumberish;
    stakedAt: BigNumberish;
    lockUntil: BigNumberish;
    isLocked: boolean;
  };

  export type StakeRecordStructOutput = [
    amount: bigint,
    stakedAt: bigint,
    lockUntil: bigint,
    isLocked: boolean
  ] & {
    amount: bigint;
    stakedAt: bigint;
    lockUntil: bigint;
    isLocked: boolean;
  };
}

export interface StakingVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_DURATION"
      | "MINIMUM_STAKE"
      | "STAKE_DEPOSIT_POINTS"
      | "admin"
      | "extendLock"
      | "getStake"
      | "hasActiveStake"
      | "pointsLedger"
      | "releaseLock"
      | "setVouchRegistry"
      | "stablecoin"
      | "stake"
      | "transferAdmin"
      | "unstake"
      | "vouchRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Staked" | "Unstaked" | "VouchRegistrySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STAKE_DEPOSIT_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "extendLock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getStake", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasActiveStake",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pointsLedger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseLock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVouchRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vouchRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STAKE_DEPOSIT_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "extendLock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsLedger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVouchRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vouchRegistry",
    data: BytesLike
  ): Result;
}

export namespace StakedEvent {
  export type InputTuple = [
    popId: BytesLike,
    amount: BigNumberish,
    stakedAt: BigNumberish
  ];
  export type OutputTuple = [popId: string, amount: bigint, stakedAt: bigint];
  export interface OutputObject {
    popId: string;
    amount: bigint;
    stakedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    popId: BytesLike,
    amount: BigNumberish,
    unstakedAt: BigNumberish
  ];
  export type OutputTuple = [popId: string, amount: bigint, unstakedAt: bigint];
  export interface OutputObject {
    popId: string;
    amount: bigint;
    unstakedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VouchRegistrySetEvent {
  export type InputTuple = [vouchRegistry: AddressLike];
  export type OutputTuple = [vouchRegistry: string];
  export interface OutputObject {
    vouchRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingVault extends BaseContract {
  connect(runner?: ContractRunner | null): StakingVault;
  waitForDeployment(): Promise<this>;

  interface: StakingVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  MINIMUM_STAKE: TypedContractMethod<[], [bigint], "view">;

  STAKE_DEPOSIT_POINTS: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  extendLock: TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;

  getStake: TypedContractMethod<
    [popId: BytesLike],
    [IStakingVault.StakeRecordStructOutput],
    "view"
  >;

  hasActiveStake: TypedContractMethod<[popId: BytesLike], [boolean], "view">;

  pointsLedger: TypedContractMethod<[], [string], "view">;

  releaseLock: TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;

  setVouchRegistry: TypedContractMethod<
    [_vouchRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  stablecoin: TypedContractMethod<[], [string], "view">;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  vouchRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMUM_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STAKE_DEPOSIT_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "extendLock"
  ): TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStake"
  ): TypedContractMethod<
    [popId: BytesLike],
    [IStakingVault.StakeRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveStake"
  ): TypedContractMethod<[popId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pointsLedger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseLock"
  ): TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVouchRegistry"
  ): TypedContractMethod<[_vouchRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vouchRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;
  getEvent(
    key: "VouchRegistrySet"
  ): TypedContractEvent<
    VouchRegistrySetEvent.InputTuple,
    VouchRegistrySetEvent.OutputTuple,
    VouchRegistrySetEvent.OutputObject
  >;

  filters: {
    "Staked(bytes32,uint128,uint64)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(bytes32,uint128,uint64)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;

    "VouchRegistrySet(address)": TypedContractEvent<
      VouchRegistrySetEvent.InputTuple,
      VouchRegistrySetEvent.OutputTuple,
      VouchRegistrySetEvent.OutputObject
    >;
    VouchRegistrySet: TypedContractEvent<
      VouchRegistrySetEvent.InputTuple,
      VouchRegistrySetEvent.OutputTuple,
      VouchRegistrySetEvent.OutputObject
    >;
  };
}
