/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DisputeResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DisputeResolver__factory>;
    getContractFactory(
      name: "IERC20D",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20D__factory>;
    getContractFactory(
      name: "IPointsLedger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPointsLedger__factory>;
    getContractFactory(
      name: "IScoreRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IScoreRegistry__factory>;
    getContractFactory(
      name: "IStakingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStakingVault__factory>;
    getContractFactory(
      name: "MockStablecoin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockStablecoin__factory>;
    getContractFactory(
      name: "PointsLedger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PointsLedger__factory>;
    getContractFactory(
      name: "ScoreRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ScoreRegistry__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "StakingVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakingVault__factory>;
    getContractFactory(
      name: "VouchRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VouchRegistry__factory>;
    getContractFactory(
      name: "WalletRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WalletRegistry__factory>;

    getContractAt(
      name: "DisputeResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DisputeResolver>;
    getContractAt(
      name: "IERC20D",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20D>;
    getContractAt(
      name: "IPointsLedger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPointsLedger>;
    getContractAt(
      name: "IScoreRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IScoreRegistry>;
    getContractAt(
      name: "IStakingVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStakingVault>;
    getContractAt(
      name: "MockStablecoin",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockStablecoin>;
    getContractAt(
      name: "PointsLedger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PointsLedger>;
    getContractAt(
      name: "ScoreRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ScoreRegistry>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "StakingVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakingVault>;
    getContractAt(
      name: "VouchRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VouchRegistry>;
    getContractAt(
      name: "WalletRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WalletRegistry>;

    deployContract(
      name: "DisputeResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeResolver>;
    deployContract(
      name: "IERC20D",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20D>;
    deployContract(
      name: "IPointsLedger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPointsLedger>;
    deployContract(
      name: "IScoreRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IScoreRegistry>;
    deployContract(
      name: "IStakingVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakingVault>;
    deployContract(
      name: "MockStablecoin",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockStablecoin>;
    deployContract(
      name: "PointsLedger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointsLedger>;
    deployContract(
      name: "ScoreRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ScoreRegistry>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "StakingVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakingVault>;
    deployContract(
      name: "VouchRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VouchRegistry>;
    deployContract(
      name: "WalletRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WalletRegistry>;

    deployContract(
      name: "DisputeResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeResolver>;
    deployContract(
      name: "IERC20D",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20D>;
    deployContract(
      name: "IPointsLedger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPointsLedger>;
    deployContract(
      name: "IScoreRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IScoreRegistry>;
    deployContract(
      name: "IStakingVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakingVault>;
    deployContract(
      name: "MockStablecoin",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockStablecoin>;
    deployContract(
      name: "PointsLedger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointsLedger>;
    deployContract(
      name: "ScoreRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ScoreRegistry>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "StakingVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakingVault>;
    deployContract(
      name: "VouchRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VouchRegistry>;
    deployContract(
      name: "WalletRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WalletRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
