/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IPointsLedger {
  export type PointsBalanceStruct = {
    total: BigNumberish;
    earned: BigNumberish;
    burned: BigNumberish;
    locked: BigNumberish;
    available: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type PointsBalanceStructOutput = [
    total: bigint,
    earned: bigint,
    burned: bigint,
    locked: bigint,
    available: bigint,
    lastUpdated: bigint
  ] & {
    total: bigint;
    earned: bigint;
    burned: bigint;
    locked: bigint;
    available: bigint;
    lastUpdated: bigint;
  };
}

export declare namespace PointsLedger {
  export type PointEventStruct = {
    amount: BigNumberish;
    timestamp: BigNumberish;
    relatedVouchId: BigNumberish;
    reason: string;
  };

  export type PointEventStructOutput = [
    amount: bigint,
    timestamp: bigint,
    relatedVouchId: bigint,
    reason: string
  ] & {
    amount: bigint;
    timestamp: bigint;
    relatedVouchId: bigint;
    reason: string;
  };
}

export interface PointsLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "authorized"
      | "burnLockedPoints"
      | "burnPoints"
      | "getBalance"
      | "getPointsEarnedInWindow"
      | "historyAt"
      | "historyLength"
      | "lockPoints"
      | "lockedPoints"
      | "mintPoints"
      | "setAuthorized"
      | "transferAdmin"
      | "unlockPoints"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedSet"
      | "PointsBurned"
      | "PointsLocked"
      | "PointsMinted"
      | "PointsUnlocked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnLockedPoints",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnPoints",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPointsEarnedInWindow",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "historyAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "historyLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockPoints",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedPoints",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintPoints",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorized",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockPoints",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnLockedPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnPoints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPointsEarnedInWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "historyAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "historyLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockPoints",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedSetEvent {
  export type InputTuple = [who: AddressLike, enabled: boolean];
  export type OutputTuple = [who: string, enabled: boolean];
  export interface OutputObject {
    who: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsBurnedEvent {
  export type InputTuple = [
    popId: BytesLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [popId: string, amount: bigint, reason: string];
  export interface OutputObject {
    popId: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsLockedEvent {
  export type InputTuple = [
    popId: BytesLike,
    amount: BigNumberish,
    vouchId: BigNumberish
  ];
  export type OutputTuple = [popId: string, amount: bigint, vouchId: bigint];
  export interface OutputObject {
    popId: string;
    amount: bigint;
    vouchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsMintedEvent {
  export type InputTuple = [
    popId: BytesLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [popId: string, amount: bigint, reason: string];
  export interface OutputObject {
    popId: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsUnlockedEvent {
  export type InputTuple = [
    popId: BytesLike,
    amount: BigNumberish,
    vouchId: BigNumberish
  ];
  export type OutputTuple = [popId: string, amount: bigint, vouchId: bigint];
  export interface OutputObject {
    popId: string;
    amount: bigint;
    vouchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PointsLedger extends BaseContract {
  connect(runner?: ContractRunner | null): PointsLedger;
  waitForDeployment(): Promise<this>;

  interface: PointsLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  authorized: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  burnLockedPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  burnPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<
    [popId: BytesLike],
    [IPointsLedger.PointsBalanceStructOutput],
    "view"
  >;

  getPointsEarnedInWindow: TypedContractMethod<
    [popId: BytesLike, fromBlock: BigNumberish, toBlock: BigNumberish],
    [bigint],
    "view"
  >;

  historyAt: TypedContractMethod<
    [popId: BytesLike, idx: BigNumberish],
    [PointsLedger.PointEventStructOutput],
    "view"
  >;

  historyLength: TypedContractMethod<[popId: BytesLike], [bigint], "view">;

  lockPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockedPoints: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  mintPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  setAuthorized: TypedContractMethod<
    [who: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorized"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "burnLockedPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [popId: BytesLike],
    [IPointsLedger.PointsBalanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPointsEarnedInWindow"
  ): TypedContractMethod<
    [popId: BytesLike, fromBlock: BigNumberish, toBlock: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "historyAt"
  ): TypedContractMethod<
    [popId: BytesLike, idx: BigNumberish],
    [PointsLedger.PointEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "historyLength"
  ): TypedContractMethod<[popId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockedPoints"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorized"
  ): TypedContractMethod<
    [who: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorizedSet"
  ): TypedContractEvent<
    AuthorizedSetEvent.InputTuple,
    AuthorizedSetEvent.OutputTuple,
    AuthorizedSetEvent.OutputObject
  >;
  getEvent(
    key: "PointsBurned"
  ): TypedContractEvent<
    PointsBurnedEvent.InputTuple,
    PointsBurnedEvent.OutputTuple,
    PointsBurnedEvent.OutputObject
  >;
  getEvent(
    key: "PointsLocked"
  ): TypedContractEvent<
    PointsLockedEvent.InputTuple,
    PointsLockedEvent.OutputTuple,
    PointsLockedEvent.OutputObject
  >;
  getEvent(
    key: "PointsMinted"
  ): TypedContractEvent<
    PointsMintedEvent.InputTuple,
    PointsMintedEvent.OutputTuple,
    PointsMintedEvent.OutputObject
  >;
  getEvent(
    key: "PointsUnlocked"
  ): TypedContractEvent<
    PointsUnlockedEvent.InputTuple,
    PointsUnlockedEvent.OutputTuple,
    PointsUnlockedEvent.OutputObject
  >;

  filters: {
    "AuthorizedSet(address,bool)": TypedContractEvent<
      AuthorizedSetEvent.InputTuple,
      AuthorizedSetEvent.OutputTuple,
      AuthorizedSetEvent.OutputObject
    >;
    AuthorizedSet: TypedContractEvent<
      AuthorizedSetEvent.InputTuple,
      AuthorizedSetEvent.OutputTuple,
      AuthorizedSetEvent.OutputObject
    >;

    "PointsBurned(bytes32,uint64,string)": TypedContractEvent<
      PointsBurnedEvent.InputTuple,
      PointsBurnedEvent.OutputTuple,
      PointsBurnedEvent.OutputObject
    >;
    PointsBurned: TypedContractEvent<
      PointsBurnedEvent.InputTuple,
      PointsBurnedEvent.OutputTuple,
      PointsBurnedEvent.OutputObject
    >;

    "PointsLocked(bytes32,uint64,uint64)": TypedContractEvent<
      PointsLockedEvent.InputTuple,
      PointsLockedEvent.OutputTuple,
      PointsLockedEvent.OutputObject
    >;
    PointsLocked: TypedContractEvent<
      PointsLockedEvent.InputTuple,
      PointsLockedEvent.OutputTuple,
      PointsLockedEvent.OutputObject
    >;

    "PointsMinted(bytes32,uint64,string)": TypedContractEvent<
      PointsMintedEvent.InputTuple,
      PointsMintedEvent.OutputTuple,
      PointsMintedEvent.OutputObject
    >;
    PointsMinted: TypedContractEvent<
      PointsMintedEvent.InputTuple,
      PointsMintedEvent.OutputTuple,
      PointsMintedEvent.OutputObject
    >;

    "PointsUnlocked(bytes32,uint64,uint64)": TypedContractEvent<
      PointsUnlockedEvent.InputTuple,
      PointsUnlockedEvent.OutputTuple,
      PointsUnlockedEvent.OutputObject
    >;
    PointsUnlocked: TypedContractEvent<
      PointsUnlockedEvent.InputTuple,
      PointsUnlockedEvent.OutputTuple,
      PointsUnlockedEvent.OutputObject
    >;
  };
}
