/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ScoreRegistry {
  export type FinalizedScoreStruct = {
    score: BigNumberish;
    totalPoints: BigNumberish;
    eventsRoot: BytesLike;
    sourceBlockHeight: BigNumberish;
    finalizedAt: BigNumberish;
    proposalId: BigNumberish;
  };

  export type FinalizedScoreStructOutput = [
    score: bigint,
    totalPoints: bigint,
    eventsRoot: string,
    sourceBlockHeight: bigint,
    finalizedAt: bigint,
    proposalId: bigint
  ] & {
    score: bigint;
    totalPoints: bigint;
    eventsRoot: string;
    sourceBlockHeight: bigint;
    finalizedAt: bigint;
    proposalId: bigint;
  };
}

export declare namespace IScoreRegistry {
  export type ScoreProposalStruct = {
    id: BigNumberish;
    popId: BytesLike;
    score: BigNumberish;
    totalPoints: BigNumberish;
    eventsRoot: BytesLike;
    eventCount: BigNumberish;
    sourceBlockHeight: BigNumberish;
    algorithmVersion: BigNumberish;
    proposedAt: BigNumberish;
    proposer: AddressLike;
    status: BigNumberish;
  };

  export type ScoreProposalStructOutput = [
    id: bigint,
    popId: string,
    score: bigint,
    totalPoints: bigint,
    eventsRoot: string,
    eventCount: bigint,
    sourceBlockHeight: bigint,
    algorithmVersion: bigint,
    proposedAt: bigint,
    proposer: string,
    status: bigint
  ] & {
    id: bigint;
    popId: string;
    score: bigint;
    totalPoints: bigint;
    eventsRoot: string;
    eventCount: bigint;
    sourceBlockHeight: bigint;
    algorithmVersion: bigint;
    proposedAt: bigint;
    proposer: string;
    status: bigint;
  };
}

export interface ScoreRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_WINDOW"
      | "MAX_SCORE"
      | "MIN_PROPOSAL_INTERVAL"
      | "admin"
      | "canFinalize"
      | "computeScore"
      | "disputeResolver"
      | "finalizeScore"
      | "getFullScore"
      | "getPendingProposal"
      | "getProposal"
      | "getScore"
      | "indexer"
      | "markDisputed"
      | "nextProposalId"
      | "proposeScore"
      | "resolveDispute"
      | "setDisputeResolver"
      | "setIndexer"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolverSet"
      | "IndexerSet"
      | "ProposalRejected"
      | "ProposalSuperseded"
      | "ScoreCorrected"
      | "ScoreDisputed"
      | "ScoreFinalized"
      | "ScoreProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_PROPOSAL_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canFinalize",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeScore",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFullScore",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getScore", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "indexer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markDisputed",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextProposalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeScore",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIndexer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PROPOSAL_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canFinalize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFullScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "indexer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextProposalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setIndexer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace DisputeResolverSetEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndexerSetEvent {
  export type InputTuple = [indexer: AddressLike];
  export type OutputTuple = [indexer: string];
  export interface OutputObject {
    indexer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRejectedEvent {
  export type InputTuple = [proposalId: BigNumberish, popId: BytesLike];
  export type OutputTuple = [proposalId: bigint, popId: string];
  export interface OutputObject {
    proposalId: bigint;
    popId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalSupersededEvent {
  export type InputTuple = [proposalId: BigNumberish, popId: BytesLike];
  export type OutputTuple = [proposalId: bigint, popId: string];
  export interface OutputObject {
    proposalId: bigint;
    popId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreCorrectedEvent {
  export type InputTuple = [
    popId: BytesLike,
    oldScore: BigNumberish,
    correctedScore: BigNumberish
  ];
  export type OutputTuple = [
    popId: string,
    oldScore: bigint,
    correctedScore: bigint
  ];
  export interface OutputObject {
    popId: string;
    oldScore: bigint;
    correctedScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreDisputedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    popId: BytesLike,
    disputeId: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    popId: string,
    disputeId: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    popId: string;
    disputeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreFinalizedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    popId: BytesLike,
    score: BigNumberish,
    finalizedAt: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    popId: string,
    score: bigint,
    finalizedAt: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    popId: string;
    score: bigint;
    finalizedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreProposedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    popId: BytesLike,
    score: BigNumberish,
    totalPoints: BigNumberish,
    eventsRoot: BytesLike,
    eventCount: BigNumberish,
    sourceBlockHeight: BigNumberish,
    algorithmVersion: BigNumberish,
    proposedAt: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    popId: string,
    score: bigint,
    totalPoints: bigint,
    eventsRoot: string,
    eventCount: bigint,
    sourceBlockHeight: bigint,
    algorithmVersion: bigint,
    proposedAt: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    popId: string;
    score: bigint;
    totalPoints: bigint;
    eventsRoot: string;
    eventCount: bigint;
    sourceBlockHeight: bigint;
    algorithmVersion: bigint;
    proposedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ScoreRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ScoreRegistry;
  waitForDeployment(): Promise<this>;

  interface: ScoreRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_PROPOSAL_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  canFinalize: TypedContractMethod<[popId: BytesLike], [boolean], "view">;

  computeScore: TypedContractMethod<
    [totalPoints: BigNumberish],
    [bigint],
    "view"
  >;

  disputeResolver: TypedContractMethod<[], [string], "view">;

  finalizeScore: TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;

  getFullScore: TypedContractMethod<
    [popId: BytesLike],
    [ScoreRegistry.FinalizedScoreStructOutput],
    "view"
  >;

  getPendingProposal: TypedContractMethod<
    [popId: BytesLike],
    [IScoreRegistry.ScoreProposalStructOutput],
    "view"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [IScoreRegistry.ScoreProposalStructOutput],
    "view"
  >;

  getScore: TypedContractMethod<
    [popId: BytesLike],
    [[bigint, bigint] & { score: bigint; updatedAt: bigint }],
    "view"
  >;

  indexer: TypedContractMethod<[], [string], "view">;

  markDisputed: TypedContractMethod<
    [popId: BytesLike, disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextProposalId: TypedContractMethod<[], [bigint], "view">;

  proposeScore: TypedContractMethod<
    [
      popId: BytesLike,
      score: BigNumberish,
      totalPoints: BigNumberish,
      eventsRoot: BytesLike,
      eventCount: BigNumberish,
      sourceBlockHeight: BigNumberish,
      algorithmVersion: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [
      popId: BytesLike,
      disputerWins: boolean,
      correctedScore: BigNumberish,
      correctedPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setDisputeResolver: TypedContractMethod<
    [newResolver: AddressLike],
    [void],
    "nonpayable"
  >;

  setIndexer: TypedContractMethod<
    [newIndexer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PROPOSAL_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canFinalize"
  ): TypedContractMethod<[popId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "computeScore"
  ): TypedContractMethod<[totalPoints: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeScore"
  ): TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getFullScore"
  ): TypedContractMethod<
    [popId: BytesLike],
    [ScoreRegistry.FinalizedScoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingProposal"
  ): TypedContractMethod<
    [popId: BytesLike],
    [IScoreRegistry.ScoreProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [IScoreRegistry.ScoreProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<
    [popId: BytesLike],
    [[bigint, bigint] & { score: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "indexer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markDisputed"
  ): TypedContractMethod<
    [popId: BytesLike, disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextProposalId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeScore"
  ): TypedContractMethod<
    [
      popId: BytesLike,
      score: BigNumberish,
      totalPoints: BigNumberish,
      eventsRoot: BytesLike,
      eventCount: BigNumberish,
      sourceBlockHeight: BigNumberish,
      algorithmVersion: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      popId: BytesLike,
      disputerWins: boolean,
      correctedScore: BigNumberish,
      correctedPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDisputeResolver"
  ): TypedContractMethod<[newResolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIndexer"
  ): TypedContractMethod<[newIndexer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DisputeResolverSet"
  ): TypedContractEvent<
    DisputeResolverSetEvent.InputTuple,
    DisputeResolverSetEvent.OutputTuple,
    DisputeResolverSetEvent.OutputObject
  >;
  getEvent(
    key: "IndexerSet"
  ): TypedContractEvent<
    IndexerSetEvent.InputTuple,
    IndexerSetEvent.OutputTuple,
    IndexerSetEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRejected"
  ): TypedContractEvent<
    ProposalRejectedEvent.InputTuple,
    ProposalRejectedEvent.OutputTuple,
    ProposalRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalSuperseded"
  ): TypedContractEvent<
    ProposalSupersededEvent.InputTuple,
    ProposalSupersededEvent.OutputTuple,
    ProposalSupersededEvent.OutputObject
  >;
  getEvent(
    key: "ScoreCorrected"
  ): TypedContractEvent<
    ScoreCorrectedEvent.InputTuple,
    ScoreCorrectedEvent.OutputTuple,
    ScoreCorrectedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreDisputed"
  ): TypedContractEvent<
    ScoreDisputedEvent.InputTuple,
    ScoreDisputedEvent.OutputTuple,
    ScoreDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreFinalized"
  ): TypedContractEvent<
    ScoreFinalizedEvent.InputTuple,
    ScoreFinalizedEvent.OutputTuple,
    ScoreFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreProposed"
  ): TypedContractEvent<
    ScoreProposedEvent.InputTuple,
    ScoreProposedEvent.OutputTuple,
    ScoreProposedEvent.OutputObject
  >;

  filters: {
    "DisputeResolverSet(address)": TypedContractEvent<
      DisputeResolverSetEvent.InputTuple,
      DisputeResolverSetEvent.OutputTuple,
      DisputeResolverSetEvent.OutputObject
    >;
    DisputeResolverSet: TypedContractEvent<
      DisputeResolverSetEvent.InputTuple,
      DisputeResolverSetEvent.OutputTuple,
      DisputeResolverSetEvent.OutputObject
    >;

    "IndexerSet(address)": TypedContractEvent<
      IndexerSetEvent.InputTuple,
      IndexerSetEvent.OutputTuple,
      IndexerSetEvent.OutputObject
    >;
    IndexerSet: TypedContractEvent<
      IndexerSetEvent.InputTuple,
      IndexerSetEvent.OutputTuple,
      IndexerSetEvent.OutputObject
    >;

    "ProposalRejected(uint64,bytes32)": TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;
    ProposalRejected: TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;

    "ProposalSuperseded(uint64,bytes32)": TypedContractEvent<
      ProposalSupersededEvent.InputTuple,
      ProposalSupersededEvent.OutputTuple,
      ProposalSupersededEvent.OutputObject
    >;
    ProposalSuperseded: TypedContractEvent<
      ProposalSupersededEvent.InputTuple,
      ProposalSupersededEvent.OutputTuple,
      ProposalSupersededEvent.OutputObject
    >;

    "ScoreCorrected(bytes32,uint64,uint64)": TypedContractEvent<
      ScoreCorrectedEvent.InputTuple,
      ScoreCorrectedEvent.OutputTuple,
      ScoreCorrectedEvent.OutputObject
    >;
    ScoreCorrected: TypedContractEvent<
      ScoreCorrectedEvent.InputTuple,
      ScoreCorrectedEvent.OutputTuple,
      ScoreCorrectedEvent.OutputObject
    >;

    "ScoreDisputed(uint64,bytes32,uint64)": TypedContractEvent<
      ScoreDisputedEvent.InputTuple,
      ScoreDisputedEvent.OutputTuple,
      ScoreDisputedEvent.OutputObject
    >;
    ScoreDisputed: TypedContractEvent<
      ScoreDisputedEvent.InputTuple,
      ScoreDisputedEvent.OutputTuple,
      ScoreDisputedEvent.OutputObject
    >;

    "ScoreFinalized(uint64,bytes32,uint64,uint64)": TypedContractEvent<
      ScoreFinalizedEvent.InputTuple,
      ScoreFinalizedEvent.OutputTuple,
      ScoreFinalizedEvent.OutputObject
    >;
    ScoreFinalized: TypedContractEvent<
      ScoreFinalizedEvent.InputTuple,
      ScoreFinalizedEvent.OutputTuple,
      ScoreFinalizedEvent.OutputObject
    >;

    "ScoreProposed(uint64,bytes32,uint64,int64,bytes32,uint32,uint64,uint16,uint64)": TypedContractEvent<
      ScoreProposedEvent.InputTuple,
      ScoreProposedEvent.OutputTuple,
      ScoreProposedEvent.OutputObject
    >;
    ScoreProposed: TypedContractEvent<
      ScoreProposedEvent.InputTuple,
      ScoreProposedEvent.OutputTuple,
      ScoreProposedEvent.OutputObject
    >;
  };
}
