/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VouchRegistry {
  export type VouchRecordStruct = {
    id: BigNumberish;
    voucher: BytesLike;
    vouchee: BytesLike;
    pointsLocked: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    status: BigNumberish;
  };

  export type VouchRecordStructOutput = [
    id: bigint,
    voucher: string,
    vouchee: string,
    pointsLocked: bigint,
    createdAt: bigint,
    expiresAt: bigint,
    status: bigint
  ] & {
    id: bigint;
    voucher: string;
    vouchee: string;
    pointsLocked: bigint;
    createdAt: bigint;
    expiresAt: bigint;
    status: bigint;
  };
}

export interface VouchRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BLOCKS_PER_MONTH"
      | "MAX_VOUCHES_PER_MONTH"
      | "MIN_VOUCHER_SCORE"
      | "POINTS_TO_LOCK"
      | "VOUCHEE_THRESHOLD"
      | "VOUCHER_DEFAULT_PENALTY"
      | "VOUCHER_SUCCESS_REWARD"
      | "VOUCH_WINDOW"
      | "activeVouchCount"
      | "admin"
      | "defaultReporter"
      | "getVouch"
      | "monthlyVouchCount"
      | "nextVouchId"
      | "pointsLedger"
      | "reportDefault"
      | "resolveVouch"
      | "setDefaultReporter"
      | "stakingVault"
      | "transferAdmin"
      | "vouch"
      | "voucheeIndex"
      | "voucherIndex"
      | "vouchesMadeBy"
      | "vouchesReceivedBy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DefaultReporterSet"
      | "VouchCreated"
      | "VouchDefaulted"
      | "VouchFailed"
      | "VouchSucceeded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BLOCKS_PER_MONTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VOUCHES_PER_MONTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOUCHER_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POINTS_TO_LOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOUCHEE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOUCHER_DEFAULT_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOUCHER_SUCCESS_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOUCH_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeVouchCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultReporter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVouch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyVouchCount",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextVouchId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pointsLedger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportDefault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveVouch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vouch", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "voucheeIndex",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voucherIndex",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vouchesMadeBy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vouchesReceivedBy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BLOCKS_PER_MONTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VOUCHES_PER_MONTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOUCHER_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POINTS_TO_LOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOUCHEE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOUCHER_DEFAULT_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOUCHER_SUCCESS_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOUCH_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeVouchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVouch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "monthlyVouchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextVouchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsLedger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveVouch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vouch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voucheeIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voucherIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vouchesMadeBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vouchesReceivedBy",
    data: BytesLike
  ): Result;
}

export namespace DefaultReporterSetEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VouchCreatedEvent {
  export type InputTuple = [
    vouchId: BigNumberish,
    voucher: BytesLike,
    vouchee: BytesLike,
    createdAt: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    vouchId: bigint,
    voucher: string,
    vouchee: string,
    createdAt: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    vouchId: bigint;
    voucher: string;
    vouchee: string;
    createdAt: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VouchDefaultedEvent {
  export type InputTuple = [vouchId: BigNumberish, vouchee: BytesLike];
  export type OutputTuple = [vouchId: bigint, vouchee: string];
  export interface OutputObject {
    vouchId: bigint;
    vouchee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VouchFailedEvent {
  export type InputTuple = [vouchId: BigNumberish];
  export type OutputTuple = [vouchId: bigint];
  export interface OutputObject {
    vouchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VouchSucceededEvent {
  export type InputTuple = [vouchId: BigNumberish];
  export type OutputTuple = [vouchId: bigint];
  export interface OutputObject {
    vouchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VouchRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VouchRegistry;
  waitForDeployment(): Promise<this>;

  interface: VouchRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BLOCKS_PER_MONTH: TypedContractMethod<[], [bigint], "view">;

  MAX_VOUCHES_PER_MONTH: TypedContractMethod<[], [bigint], "view">;

  MIN_VOUCHER_SCORE: TypedContractMethod<[], [bigint], "view">;

  POINTS_TO_LOCK: TypedContractMethod<[], [bigint], "view">;

  VOUCHEE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  VOUCHER_DEFAULT_PENALTY: TypedContractMethod<[], [bigint], "view">;

  VOUCHER_SUCCESS_REWARD: TypedContractMethod<[], [bigint], "view">;

  VOUCH_WINDOW: TypedContractMethod<[], [bigint], "view">;

  activeVouchCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  defaultReporter: TypedContractMethod<[], [string], "view">;

  getVouch: TypedContractMethod<
    [vouchId: BigNumberish],
    [VouchRegistry.VouchRecordStructOutput],
    "view"
  >;

  monthlyVouchCount: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  nextVouchId: TypedContractMethod<[], [bigint], "view">;

  pointsLedger: TypedContractMethod<[], [string], "view">;

  reportDefault: TypedContractMethod<
    [vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveVouch: TypedContractMethod<
    [vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingVault: TypedContractMethod<[], [string], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  vouch: TypedContractMethod<[voucheePopId: BytesLike], [bigint], "nonpayable">;

  voucheeIndex: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  voucherIndex: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  vouchesMadeBy: TypedContractMethod<[popId: BytesLike], [bigint[]], "view">;

  vouchesReceivedBy: TypedContractMethod<
    [popId: BytesLike],
    [bigint[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BLOCKS_PER_MONTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VOUCHES_PER_MONTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOUCHER_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POINTS_TO_LOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOUCHEE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOUCHER_DEFAULT_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOUCHER_SUCCESS_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOUCH_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeVouchCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultReporter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getVouch"
  ): TypedContractMethod<
    [vouchId: BigNumberish],
    [VouchRegistry.VouchRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "monthlyVouchCount"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextVouchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pointsLedger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportDefault"
  ): TypedContractMethod<[vouchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveVouch"
  ): TypedContractMethod<[vouchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vouch"
  ): TypedContractMethod<[voucheePopId: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "voucheeIndex"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voucherIndex"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "vouchesMadeBy"
  ): TypedContractMethod<[popId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "vouchesReceivedBy"
  ): TypedContractMethod<[popId: BytesLike], [bigint[]], "view">;

  getEvent(
    key: "DefaultReporterSet"
  ): TypedContractEvent<
    DefaultReporterSetEvent.InputTuple,
    DefaultReporterSetEvent.OutputTuple,
    DefaultReporterSetEvent.OutputObject
  >;
  getEvent(
    key: "VouchCreated"
  ): TypedContractEvent<
    VouchCreatedEvent.InputTuple,
    VouchCreatedEvent.OutputTuple,
    VouchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VouchDefaulted"
  ): TypedContractEvent<
    VouchDefaultedEvent.InputTuple,
    VouchDefaultedEvent.OutputTuple,
    VouchDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "VouchFailed"
  ): TypedContractEvent<
    VouchFailedEvent.InputTuple,
    VouchFailedEvent.OutputTuple,
    VouchFailedEvent.OutputObject
  >;
  getEvent(
    key: "VouchSucceeded"
  ): TypedContractEvent<
    VouchSucceededEvent.InputTuple,
    VouchSucceededEvent.OutputTuple,
    VouchSucceededEvent.OutputObject
  >;

  filters: {
    "DefaultReporterSet(address)": TypedContractEvent<
      DefaultReporterSetEvent.InputTuple,
      DefaultReporterSetEvent.OutputTuple,
      DefaultReporterSetEvent.OutputObject
    >;
    DefaultReporterSet: TypedContractEvent<
      DefaultReporterSetEvent.InputTuple,
      DefaultReporterSetEvent.OutputTuple,
      DefaultReporterSetEvent.OutputObject
    >;

    "VouchCreated(uint64,bytes32,bytes32,uint64,uint64)": TypedContractEvent<
      VouchCreatedEvent.InputTuple,
      VouchCreatedEvent.OutputTuple,
      VouchCreatedEvent.OutputObject
    >;
    VouchCreated: TypedContractEvent<
      VouchCreatedEvent.InputTuple,
      VouchCreatedEvent.OutputTuple,
      VouchCreatedEvent.OutputObject
    >;

    "VouchDefaulted(uint64,bytes32)": TypedContractEvent<
      VouchDefaultedEvent.InputTuple,
      VouchDefaultedEvent.OutputTuple,
      VouchDefaultedEvent.OutputObject
    >;
    VouchDefaulted: TypedContractEvent<
      VouchDefaultedEvent.InputTuple,
      VouchDefaultedEvent.OutputTuple,
      VouchDefaultedEvent.OutputObject
    >;

    "VouchFailed(uint64)": TypedContractEvent<
      VouchFailedEvent.InputTuple,
      VouchFailedEvent.OutputTuple,
      VouchFailedEvent.OutputObject
    >;
    VouchFailed: TypedContractEvent<
      VouchFailedEvent.InputTuple,
      VouchFailedEvent.OutputTuple,
      VouchFailedEvent.OutputObject
    >;

    "VouchSucceeded(uint64)": TypedContractEvent<
      VouchSucceededEvent.InputTuple,
      VouchSucceededEvent.OutputTuple,
      VouchSucceededEvent.OutputObject
    >;
    VouchSucceeded: TypedContractEvent<
      VouchSucceededEvent.InputTuple,
      VouchSucceededEvent.OutputTuple,
      VouchSucceededEvent.OutputObject
    >;
  };
}
