/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace WalletRegistry {
  export type WalletLinkStruct = {
    chainId: BigNumberish;
    addressBytes: BytesLike;
    registeredAt: BigNumberish;
    isActive: boolean;
    signature: BytesLike;
  };

  export type WalletLinkStructOutput = [
    chainId: bigint,
    addressBytes: string,
    registeredAt: bigint,
    isActive: boolean,
    signature: string
  ] & {
    chainId: bigint;
    addressBytes: string;
    registeredAt: bigint;
    isActive: boolean;
    signature: string;
  };
}

export interface WalletRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getLinks"
      | "linkMessage"
      | "popIdForWallet"
      | "registerWallet"
      | "revokeWallet"
      | "transferAdmin"
      | "walletToPopId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "WalletRegistered" | "WalletRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "getLinks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "linkMessage",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "popIdForWallet",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerWallet",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeWallet",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "walletToPopId",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLinks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "linkMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "popIdForWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletToPopId",
    data: BytesLike
  ): Result;
}

export namespace WalletRegisteredEvent {
  export type InputTuple = [
    popId: BytesLike,
    chainId: BigNumberish,
    addressBytes: BytesLike
  ];
  export type OutputTuple = [
    popId: string,
    chainId: bigint,
    addressBytes: string
  ];
  export interface OutputObject {
    popId: string;
    chainId: bigint;
    addressBytes: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletRevokedEvent {
  export type InputTuple = [
    popId: BytesLike,
    chainId: BigNumberish,
    addressBytes: BytesLike
  ];
  export type OutputTuple = [
    popId: string,
    chainId: bigint,
    addressBytes: string
  ];
  export interface OutputObject {
    popId: string;
    chainId: bigint;
    addressBytes: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WalletRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WalletRegistry;
  waitForDeployment(): Promise<this>;

  interface: WalletRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getLinks: TypedContractMethod<
    [popId: BytesLike],
    [WalletRegistry.WalletLinkStructOutput[]],
    "view"
  >;

  linkMessage: TypedContractMethod<
    [popId: BytesLike, chainId: BigNumberish, addressBytes: BytesLike],
    [string],
    "view"
  >;

  popIdForWallet: TypedContractMethod<
    [chainId: BigNumberish, addressBytes: BytesLike],
    [string],
    "view"
  >;

  registerWallet: TypedContractMethod<
    [chainId: BigNumberish, addressBytes: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeWallet: TypedContractMethod<
    [chainId: BigNumberish, addressBytes: BytesLike],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  walletToPopId: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLinks"
  ): TypedContractMethod<
    [popId: BytesLike],
    [WalletRegistry.WalletLinkStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "linkMessage"
  ): TypedContractMethod<
    [popId: BytesLike, chainId: BigNumberish, addressBytes: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "popIdForWallet"
  ): TypedContractMethod<
    [chainId: BigNumberish, addressBytes: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerWallet"
  ): TypedContractMethod<
    [chainId: BigNumberish, addressBytes: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeWallet"
  ): TypedContractMethod<
    [chainId: BigNumberish, addressBytes: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "walletToPopId"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [string],
    "view"
  >;

  getEvent(
    key: "WalletRegistered"
  ): TypedContractEvent<
    WalletRegisteredEvent.InputTuple,
    WalletRegisteredEvent.OutputTuple,
    WalletRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "WalletRevoked"
  ): TypedContractEvent<
    WalletRevokedEvent.InputTuple,
    WalletRevokedEvent.OutputTuple,
    WalletRevokedEvent.OutputObject
  >;

  filters: {
    "WalletRegistered(bytes32,uint32,bytes32)": TypedContractEvent<
      WalletRegisteredEvent.InputTuple,
      WalletRegisteredEvent.OutputTuple,
      WalletRegisteredEvent.OutputObject
    >;
    WalletRegistered: TypedContractEvent<
      WalletRegisteredEvent.InputTuple,
      WalletRegisteredEvent.OutputTuple,
      WalletRegisteredEvent.OutputObject
    >;

    "WalletRevoked(bytes32,uint32,bytes32)": TypedContractEvent<
      WalletRevokedEvent.InputTuple,
      WalletRevokedEvent.OutputTuple,
      WalletRevokedEvent.OutputObject
    >;
    WalletRevoked: TypedContractEvent<
      WalletRevokedEvent.InputTuple,
      WalletRevokedEvent.OutputTuple,
      WalletRevokedEvent.OutputObject
    >;
  };
}
