/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DisputeResolver {
  export type DisputeEvidenceStruct = {
    eventSourceChain: BigNumberish;
    eventBlockNumber: BigNumberish;
    eventIndex: BigNumberish;
    eventData: BytesLike;
    expectedPoints: BigNumberish;
    expectedReasonCode: string;
    merkleProof: BytesLike[];
    leafIndex: BigNumberish;
    leafData: BytesLike;
    leafHash: BytesLike;
    disqualifyingReason: string;
    claimedCorrectPoints: BigNumberish;
    claimedCorrectScore: BigNumberish;
  };

  export type DisputeEvidenceStructOutput = [
    eventSourceChain: bigint,
    eventBlockNumber: bigint,
    eventIndex: bigint,
    eventData: string,
    expectedPoints: bigint,
    expectedReasonCode: string,
    merkleProof: string[],
    leafIndex: bigint,
    leafData: string,
    leafHash: string,
    disqualifyingReason: string,
    claimedCorrectPoints: bigint,
    claimedCorrectScore: bigint
  ] & {
    eventSourceChain: bigint;
    eventBlockNumber: bigint;
    eventIndex: bigint;
    eventData: string;
    expectedPoints: bigint;
    expectedReasonCode: string;
    merkleProof: string[];
    leafIndex: bigint;
    leafData: string;
    leafHash: string;
    disqualifyingReason: string;
    claimedCorrectPoints: bigint;
    claimedCorrectScore: bigint;
  };

  export type DisputeStruct = {
    id: BigNumberish;
    popId: BytesLike;
    proposalId: BigNumberish;
    disputer: AddressLike;
    bond: BigNumberish;
    claimType: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type DisputeStructOutput = [
    id: bigint,
    popId: string,
    proposalId: bigint,
    disputer: string,
    bond: bigint,
    claimType: bigint,
    status: bigint,
    createdAt: bigint,
    resolvedAt: bigint
  ] & {
    id: bigint;
    popId: string;
    proposalId: bigint;
    disputer: string;
    bond: bigint;
    claimType: bigint;
    status: bigint;
    createdAt: bigint;
    resolvedAt: bigint;
  };
}

export interface DisputeResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_BOND"
      | "DISPUTE_REWARD"
      | "RESOLUTION_WINDOW"
      | "admin"
      | "dispute"
      | "fundReward"
      | "getDispute"
      | "getEvidence"
      | "governance"
      | "nextDisputeId"
      | "openDisputeByProposal"
      | "resolveDispute"
      | "scoreRegistry"
      | "setGovernance"
      | "setTreasury"
      | "stablecoin"
      | "transferAdmin"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondForfeited"
      | "BondRefunded"
      | "DisputeCreated"
      | "DisputeResolved"
      | "GovernanceSet"
      | "IndexerPenalized"
      | "TreasurySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESOLUTION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dispute",
    values: [BytesLike, BigNumberish, DisputeResolver.DisputeEvidenceStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "fundReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextDisputeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDisputeByProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESOLUTION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextDisputeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDisputeByProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace BondForfeitedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [disputeId: bigint, amount: bigint, to: string];
  export interface OutputObject {
    disputeId: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondRefundedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [disputeId: bigint, amount: bigint, to: string];
  export interface OutputObject {
    disputeId: bigint;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    popId: BytesLike,
    proposalId: BigNumberish,
    claimType: BigNumberish,
    disputer: AddressLike
  ];
  export type OutputTuple = [
    disputeId: bigint,
    popId: string,
    proposalId: bigint,
    claimType: bigint,
    disputer: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    popId: string;
    proposalId: bigint;
    claimType: bigint;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    disputerWon: boolean,
    popId: BytesLike
  ];
  export type OutputTuple = [
    disputeId: bigint,
    disputerWon: boolean,
    popId: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    disputerWon: boolean;
    popId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceSetEvent {
  export type InputTuple = [governance: AddressLike];
  export type OutputTuple = [governance: string];
  export interface OutputObject {
    governance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndexerPenalizedEvent {
  export type InputTuple = [proposalId: BigNumberish, reason: string];
  export type OutputTuple = [proposalId: bigint, reason: string];
  export interface OutputObject {
    proposalId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DisputeResolver extends BaseContract {
  connect(runner?: ContractRunner | null): DisputeResolver;
  waitForDeployment(): Promise<this>;

  interface: DisputeResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_BOND: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_REWARD: TypedContractMethod<[], [bigint], "view">;

  RESOLUTION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  dispute: TypedContractMethod<
    [
      popId: BytesLike,
      claimType: BigNumberish,
      evidence: DisputeResolver.DisputeEvidenceStruct
    ],
    [bigint],
    "nonpayable"
  >;

  fundReward: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getDispute: TypedContractMethod<
    [disputeId: BigNumberish],
    [DisputeResolver.DisputeStructOutput],
    "view"
  >;

  getEvidence: TypedContractMethod<
    [disputeId: BigNumberish],
    [DisputeResolver.DisputeEvidenceStructOutput],
    "view"
  >;

  governance: TypedContractMethod<[], [string], "view">;

  nextDisputeId: TypedContractMethod<[], [bigint], "view">;

  openDisputeByProposal: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [
      disputeId: BigNumberish,
      disputerWins: boolean,
      correctedScore: BigNumberish,
      correctedPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scoreRegistry: TypedContractMethod<[], [string], "view">;

  setGovernance: TypedContractMethod<[g: AddressLike], [void], "nonpayable">;

  setTreasury: TypedContractMethod<[t: AddressLike], [void], "nonpayable">;

  stablecoin: TypedContractMethod<[], [string], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLUTION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<
    [
      popId: BytesLike,
      claimType: BigNumberish,
      evidence: DisputeResolver.DisputeEvidenceStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundReward"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [disputeId: BigNumberish],
    [DisputeResolver.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [disputeId: BigNumberish],
    [DisputeResolver.DisputeEvidenceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextDisputeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openDisputeByProposal"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      disputeId: BigNumberish,
      disputerWins: boolean,
      correctedScore: BigNumberish,
      correctedPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scoreRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGovernance"
  ): TypedContractMethod<[g: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[t: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BondForfeited"
  ): TypedContractEvent<
    BondForfeitedEvent.InputTuple,
    BondForfeitedEvent.OutputTuple,
    BondForfeitedEvent.OutputObject
  >;
  getEvent(
    key: "BondRefunded"
  ): TypedContractEvent<
    BondRefundedEvent.InputTuple,
    BondRefundedEvent.OutputTuple,
    BondRefundedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceSet"
  ): TypedContractEvent<
    GovernanceSetEvent.InputTuple,
    GovernanceSetEvent.OutputTuple,
    GovernanceSetEvent.OutputObject
  >;
  getEvent(
    key: "IndexerPenalized"
  ): TypedContractEvent<
    IndexerPenalizedEvent.InputTuple,
    IndexerPenalizedEvent.OutputTuple,
    IndexerPenalizedEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;

  filters: {
    "BondForfeited(uint64,uint128,address)": TypedContractEvent<
      BondForfeitedEvent.InputTuple,
      BondForfeitedEvent.OutputTuple,
      BondForfeitedEvent.OutputObject
    >;
    BondForfeited: TypedContractEvent<
      BondForfeitedEvent.InputTuple,
      BondForfeitedEvent.OutputTuple,
      BondForfeitedEvent.OutputObject
    >;

    "BondRefunded(uint64,uint128,address)": TypedContractEvent<
      BondRefundedEvent.InputTuple,
      BondRefundedEvent.OutputTuple,
      BondRefundedEvent.OutputObject
    >;
    BondRefunded: TypedContractEvent<
      BondRefundedEvent.InputTuple,
      BondRefundedEvent.OutputTuple,
      BondRefundedEvent.OutputObject
    >;

    "DisputeCreated(uint64,bytes32,uint64,uint8,address)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeResolved(uint64,bool,bytes32)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "GovernanceSet(address)": TypedContractEvent<
      GovernanceSetEvent.InputTuple,
      GovernanceSetEvent.OutputTuple,
      GovernanceSetEvent.OutputObject
    >;
    GovernanceSet: TypedContractEvent<
      GovernanceSetEvent.InputTuple,
      GovernanceSetEvent.OutputTuple,
      GovernanceSetEvent.OutputObject
    >;

    "IndexerPenalized(uint64,string)": TypedContractEvent<
      IndexerPenalizedEvent.InputTuple,
      IndexerPenalizedEvent.OutputTuple,
      IndexerPenalizedEvent.OutputObject
    >;
    IndexerPenalized: TypedContractEvent<
      IndexerPenalizedEvent.InputTuple,
      IndexerPenalizedEvent.OutputTuple,
      IndexerPenalizedEvent.OutputObject
    >;

    "TreasurySet(address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
  };
}
