/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DisputeResolver__factory } from "./DisputeResolver__factory";
export { IERC20D__factory } from "./IERC20D__factory";
