/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPointsLedger } from "./IPointsLedger";
export type { IScoreRegistry } from "./IScoreRegistry";
export type { IStakingVault } from "./IStakingVault";
