/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IPointsLedger {
  export type PointsBalanceStruct = {
    total: BigNumberish;
    earned: BigNumberish;
    burned: BigNumberish;
    locked: BigNumberish;
    available: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type PointsBalanceStructOutput = [
    total: bigint,
    earned: bigint,
    burned: bigint,
    locked: bigint,
    available: bigint,
    lastUpdated: bigint
  ] & {
    total: bigint;
    earned: bigint;
    burned: bigint;
    locked: bigint;
    available: bigint;
    lastUpdated: bigint;
  };
}

export interface IPointsLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnLockedPoints"
      | "burnPoints"
      | "getBalance"
      | "getPointsEarnedInWindow"
      | "lockPoints"
      | "mintPoints"
      | "unlockPoints"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "burnLockedPoints",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnPoints",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPointsEarnedInWindow",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockPoints",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintPoints",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockPoints",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "burnLockedPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnPoints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPointsEarnedInWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockPoints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockPoints",
    data: BytesLike
  ): Result;
}

export interface IPointsLedger extends BaseContract {
  connect(runner?: ContractRunner | null): IPointsLedger;
  waitForDeployment(): Promise<this>;

  interface: IPointsLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnLockedPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  burnPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<
    [popId: BytesLike],
    [IPointsLedger.PointsBalanceStructOutput],
    "view"
  >;

  getPointsEarnedInWindow: TypedContractMethod<
    [popId: BytesLike, fromBlock: BigNumberish, toBlock: BigNumberish],
    [bigint],
    "view"
  >;

  lockPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  unlockPoints: TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnLockedPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [popId: BytesLike],
    [IPointsLedger.PointsBalanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPointsEarnedInWindow"
  ): TypedContractMethod<
    [popId: BytesLike, fromBlock: BigNumberish, toBlock: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockPoints"
  ): TypedContractMethod<
    [popId: BytesLike, amount: BigNumberish, vouchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
