/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IScoreRegistry {
  export type ScoreProposalStruct = {
    id: BigNumberish;
    popId: BytesLike;
    score: BigNumberish;
    totalPoints: BigNumberish;
    eventsRoot: BytesLike;
    eventCount: BigNumberish;
    sourceBlockHeight: BigNumberish;
    algorithmVersion: BigNumberish;
    proposedAt: BigNumberish;
    proposer: AddressLike;
    status: BigNumberish;
  };

  export type ScoreProposalStructOutput = [
    id: bigint,
    popId: string,
    score: bigint,
    totalPoints: bigint,
    eventsRoot: string,
    eventCount: bigint,
    sourceBlockHeight: bigint,
    algorithmVersion: bigint,
    proposedAt: bigint,
    proposer: string,
    status: bigint
  ] & {
    id: bigint;
    popId: string;
    score: bigint;
    totalPoints: bigint;
    eventsRoot: string;
    eventCount: bigint;
    sourceBlockHeight: bigint;
    algorithmVersion: bigint;
    proposedAt: bigint;
    proposer: string;
    status: bigint;
  };
}

export interface IScoreRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_WINDOW"
      | "getPendingProposal"
      | "markDisputed"
      | "resolveDispute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markDisputed",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
}

export interface IScoreRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IScoreRegistry;
  waitForDeployment(): Promise<this>;

  interface: IScoreRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  getPendingProposal: TypedContractMethod<
    [popId: BytesLike],
    [IScoreRegistry.ScoreProposalStructOutput],
    "view"
  >;

  markDisputed: TypedContractMethod<
    [popId: BytesLike, disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [
      popId: BytesLike,
      disputerWins: boolean,
      correctedScore: BigNumberish,
      correctedPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingProposal"
  ): TypedContractMethod<
    [popId: BytesLike],
    [IScoreRegistry.ScoreProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDisputed"
  ): TypedContractMethod<
    [popId: BytesLike, disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      popId: BytesLike,
      disputerWins: boolean,
      correctedScore: BigNumberish,
      correctedPoints: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
