/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IStakingVault {
  export type StakeRecordStruct = {
    amount: BigNumberish;
    stakedAt: BigNumberish;
    lockUntil: BigNumberish;
    isLocked: boolean;
  };

  export type StakeRecordStructOutput = [
    amount: bigint,
    stakedAt: bigint,
    lockUntil: bigint,
    isLocked: boolean
  ] & {
    amount: bigint;
    stakedAt: bigint;
    lockUntil: bigint;
    isLocked: boolean;
  };
}

export interface IStakingVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "extendLock"
      | "getStake"
      | "hasActiveStake"
      | "releaseLock"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "extendLock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getStake", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasActiveStake",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseLock",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "extendLock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseLock",
    data: BytesLike
  ): Result;
}

export interface IStakingVault extends BaseContract {
  connect(runner?: ContractRunner | null): IStakingVault;
  waitForDeployment(): Promise<this>;

  interface: IStakingVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  extendLock: TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;

  getStake: TypedContractMethod<
    [popId: BytesLike],
    [IStakingVault.StakeRecordStructOutput],
    "view"
  >;

  hasActiveStake: TypedContractMethod<[popId: BytesLike], [boolean], "view">;

  releaseLock: TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "extendLock"
  ): TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStake"
  ): TypedContractMethod<
    [popId: BytesLike],
    [IStakingVault.StakeRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveStake"
  ): TypedContractMethod<[popId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "releaseLock"
  ): TypedContractMethod<[popId: BytesLike], [void], "nonpayable">;

  filters: {};
}
